/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.55
 * Generated at: 2020-07-28 07:59:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.tiles2.emp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.highcharts.com/highcharts.js\"></script>\r\n");
      out.write("<script src=\"https://code.highcharts.com/modules/exporting.js\"></script>\r\n");
      out.write("<script src=\"https://code.highcharts.com/modules/export-data.js\"></script>\r\n");
      out.write("<script src=\"https://code.highcharts.com/modules/accessibility.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t.highcharts-figure, .highcharts-data-table table {\r\n");
      out.write("\t    min-width: 320px; \r\n");
      out.write("\t    max-width: 800px;\r\n");
      out.write("\t    margin: 1em auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.highcharts-data-table table {\r\n");
      out.write("\t\tfont-family: Verdana, sans-serif;\r\n");
      out.write("\t\tborder-collapse: collapse;\r\n");
      out.write("\t\tborder: 1px solid #EBEBEB;\r\n");
      out.write("\t\tmargin: 10px auto;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\tmax-width: 500px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.highcharts-data-table caption {\r\n");
      out.write("\t    padding: 1em 0;\r\n");
      out.write("\t    font-size: 1.2em;\r\n");
      out.write("\t    color: #555;\r\n");
      out.write("\t}\r\n");
      out.write("\t.highcharts-data-table th {\r\n");
      out.write("\t\tfont-weight: 600;\r\n");
      out.write("\t    padding: 0.5em;\r\n");
      out.write("\t}\r\n");
      out.write("\t.highcharts-data-table td, .highcharts-data-table th, .highcharts-data-table caption {\r\n");
      out.write("\t    padding: 0.5em;\r\n");
      out.write("\t}\r\n");
      out.write("\t.highcharts-data-table thead tr, .highcharts-data-table tr:nth-child(even) {\r\n");
      out.write("\t    background: #f8f8f8;\r\n");
      out.write("\t}\r\n");
      out.write("\t.highcharts-data-table tr:hover {\r\n");
      out.write("\t    background: #f1f7ff;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tinput[type=\"number\"] {\r\n");
      out.write("\t\tmin-width: 50px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<figure class=\"highcharts-figure\">\r\n");
      out.write("    <div id=\"chart_container\"></div>\r\n");
      out.write("    <p class=\"highcharts-description\">\r\n");
      out.write("        Pie charts are very popular for showing a compact overview of a\r\n");
      out.write("        composition or comparison. While they can be harder to read than\r\n");
      out.write("        column charts, they remain a popular choice for small datasets.\r\n");
      out.write("    </p>\r\n");
      out.write("</figure>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tHighcharts.chart('chart_container', {\r\n");
      out.write("\t\t    chart: {\r\n");
      out.write("\t\t        plotBackgroundColor: null,\r\n");
      out.write("\t\t        plotBorderWidth: null,\r\n");
      out.write("\t\t        plotShadow: false,\r\n");
      out.write("\t\t        type: 'pie'\r\n");
      out.write("\t\t    },\r\n");
      out.write("\t\t    title: {\r\n");
      out.write("\t\t        text: '브라우저 시장 점유율 2020년 07월 기준'\r\n");
      out.write("\t\t    },\r\n");
      out.write("\t\t    tooltip: {\r\n");
      out.write("\t\t        pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'\r\n");
      out.write("\t\t    },\r\n");
      out.write("\t\t    accessibility: {\r\n");
      out.write("\t\t        point: {\r\n");
      out.write("\t\t            valueSuffix: '%'\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    },\r\n");
      out.write("\t\t    plotOptions: {\r\n");
      out.write("\t\t        pie: {\r\n");
      out.write("\t\t            allowPointSelect: true,\r\n");
      out.write("\t\t            cursor: 'pointer',\r\n");
      out.write("\t\t            dataLabels: {\r\n");
      out.write("\t\t                enabled: true,\r\n");
      out.write("\t\t                format: '<b>{point.name}</b>: {point.percentage:.1f} %'\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    },\r\n");
      out.write("\t\t    series: [{\r\n");
      out.write("\t\t        name: 'Brands',\r\n");
      out.write("\t\t        colorByPoint: true,\r\n");
      out.write("\t\t        data: [{\r\n");
      out.write("\t\t            name: 'Chrome',\r\n");
      out.write("\t\t            y: 61.41,\r\n");
      out.write("\t\t            sliced: true,\r\n");
      out.write("\t\t            selected: true\r\n");
      out.write("\t\t        }, {\r\n");
      out.write("\t\t            name: 'Internet Explorer',\r\n");
      out.write("\t\t            y: 11.84\r\n");
      out.write("\t\t        }, {\r\n");
      out.write("\t\t            name: 'Firefox',\r\n");
      out.write("\t\t            y: 10.85\r\n");
      out.write("\t\t        }, {\r\n");
      out.write("\t\t            name: 'Edge',\r\n");
      out.write("\t\t            y: 4.67\r\n");
      out.write("\t\t        }, {\r\n");
      out.write("\t\t            name: 'Safari',\r\n");
      out.write("\t\t            y: 4.18\r\n");
      out.write("\t\t        }, {\r\n");
      out.write("\t\t            name: 'Sogou Explorer',\r\n");
      out.write("\t\t            y: 1.64\r\n");
      out.write("\t\t        }, {\r\n");
      out.write("\t\t            name: 'Opera',\r\n");
      out.write("\t\t            y: 1.6\r\n");
      out.write("\t\t        }, {\r\n");
      out.write("\t\t            name: 'QQ',\r\n");
      out.write("\t\t            y: 1.2\r\n");
      out.write("\t\t        }, {\r\n");
      out.write("\t\t            name: 'Other',\r\n");
      out.write("\t\t            y: 2.61\r\n");
      out.write("\t\t        }]\r\n");
      out.write("\t\t    }]\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}); // end of $(document).ready(function(){})---------------------------\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
